version: 2
jobs:
  test:
    docker:
    - image: circleci/node:9.9.0
      environment:
        TZ: Asia/Tokyo
    steps:
    - checkout
    - restore_cache:
        key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
        name: npmのライブラリインストール
        command: npm install
    - save_cache:
        key: npm-cache-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
    - run:
        name: テスト実行
        command: npm test

  deploy:
    docker:
    - image: circleci/node:9.9.0
      environment:
        TZ: Asia/Tokyo
    steps:
    - checkout
    - run:
        name: ダミー
        command: echo 'deployはまだしません。'

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          filters:
            tags:
              only: /^[0-9].*/
            branches:
              ignore: /.*/
