version: 2.1

orbs:
  discord: antonioned/discord@0.1.0  

jobs:
  test:
    docker:
    - image: cimg/node:19.2.0
      environment:
        TZ: Asia/Tokyo
    steps:
    - checkout
    - restore_cache:
        key: npm-cache-{{ checksum "package-lock.json" }}
    - run:
        name: npmのライブラリインストール
        command: npm install
    - save_cache:
        key: npm-cache-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
    - run:
        name: テスト実行
        command: npm test
    - discord/status:
        fail_only: true
        failure_message: "Project: **${CIRCLE_PROJECT_REPONAME}**\\nTriggered User: **${CIRCLE_USERNAME}**\\n\\nテストに失敗しました。 JOB: **$CIRCLE_JOB**"
        webhook: "${DISCORD_WEBHOOK}"

  deploy:
    docker:
    - image: cimg/node:19.2.0
      environment:
        TZ: Asia/Tokyo
    steps:
    - checkout
    - restore_cache:
        key: npm-cache-{{ checksum "package-lock.json" }}
    - run:
        name: npmのライブラリインストール
        command: npm install
    - save_cache:
        key: npm-cache-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
    - run:
        name: claspの「ログイン状態の設定ファイル」を復元
        command: echo ${CLASP_LOGGEDIN_FILE_CONTENTS} > ~/.clasprc.json
    - run:
        name: GoogleAppScriptとしてデプロイ
        command: npm run deploy
    - discord/status:
        fail_only: true
        failure_message: "Project: **${CIRCLE_PROJECT_REPONAME}**\\nTriggered User: **${CIRCLE_USERNAME}**\\n\\nデプロイに失敗しました。 JOB: **$CIRCLE_JOB**"
        webhook: "${DISCORD_WEBHOOK}"

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: kazuhito_m-products

  deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: kazuhito_m-products
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: kazuhito_m-products
